name: sonar scan

on:
 workflow_call:

jobs:
  sonar:
   runs-on: self-hosted

   steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'adopt'
    - name: SonarQubeScan
      run: mvn -B verify sonar:sonar -Dsonar.projectKey=nitin2925_Devsecops-pipeline -Dsonar.organization=nitin2925 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      env: 
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    
