name: sonar scan

on:
 workflow_call:

jobs:
  sonar:
   runs-on: self-hosted

   steps:
    - name: SonarQubeScan
      uses: SonarSource/sonarqube-scan-action@v4
      env: 
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
